### PR TITLE
Added the Eb openings page to the website

### LINKED ISSUE #8: Add EBOpenings
Link: https://www.oscvitap.org/ebopenings

For Upcoming EB Openings

New Feature. Details:

- Cards that display roles open
- Apply Button
- Link it to the EB Google Forms

### PR DESCRIPTION
**Pull request by ashu168**
### Changes introduced in this pull request.

- [x] Cards for each role in EB added with the label of position vacant or not and a apply button to any particular card when any role is vacant.

- [x] The vacancy of any role can be changed in the array of roles in EBopeninglayout.js file.
### Connected Issue

- resolved #8 

image

### CODE REVIEW

**Comment by kode-logger** [comment]
@ashu168 Can you add a gap between the div and the footer?


image

**Review by kode-logger — COMMENTED** [review]
Everything seems good, Waiting for Admin Department's opinion. Will merge it after the verification 👍🏼.
Thank you for your hard work 😁.

**Review by SVijayB — APPROVED** [review]
Overall page layout looks good but there are a few changes.
- [x] Add HR department as well (I know it's just a template but add in the HR department as well)
- [x] Add in a link to redirect to ebopenings on the teams page (not just footer).

**Review by SVijayB — APPROVED** [review]
Changes look good. Requested changes were made. 
Approving for a merge from my side. 
Good work @ashu168 🚀

**Pull request merged**
